### PR TITLE
develop->master (TASK-740)

### PR DESCRIPTION
**Pull request by kkellerlbl**
Merge to master for changing next branch deploy to master.

### CODE REVIEW

**Comment by MrCreosote** [comment]
@kkellerlbl What's running where now? 

@rsutormin you might want to look at this, most of the changes are yours

**Comment by MrCreosote** [comment]
OMG this is a year's worth of commits.

**Comment by kkellerlbl** [comment]
develop is currently on next (and therefore appdev and prod).

-- 
Keith Keller
Environmental Genomics and Systems Biology Division
(sent from mobile)

**Comment by MrCreosote** [comment]
OK, so this is not actually making any changes to any environments, so seems fine.

**Comment by kkellerlbl** [comment]
Yeah, it looks like a lot because we haven't been keeping master up to date (since staging was used for a while for next and appdev/prod).

All of these changes are going to go up on next before going anywhere else.  So we'll be able to figure out if we broke something before we put something up in production.

**Pull request merged**
