### PR TITLE
 Develop->staging

### PR DESCRIPTION
**Pull request by kkellerlbl**
Promote to staging in preparation for next production release.  In particular we want the njs job runner change which reports AWE_CLIENTNAME.

### CODE REVIEW

**Comment by kkellerlbl** [comment]
@rsutormin @MrCreosote can you review these and see if there are any problems with promoting this up now?  There's a lot more changes than I anticipated.

**Comment by kkellerlbl** [comment]
Relates to TASK-233.

**Comment by MrCreosote** [comment]
I checked my changes; all except 1 is in the db update script which is now obsolete since all DBs have been updated. The other change is completely trivial: https://github.com/kbase/njs_wrapper/pull/68/commits/834dd85c7af934cf2f9dd35ce13fc83324181599

**Comment by kkellerlbl** [comment]
See #69.

**Pull request closed without merging**
