### PR TITLE
Merge to master

### PR DESCRIPTION
**Pull request by kkellerlbl**
Do we feel ready to move this to master to be able to properly deploy to next?

### CODE REVIEW

**Comment by bio-boris** [comment]
@kkellerlbl We need to have a user created with Read/Write access to the UJS database on Next. Does that Exist?

**Comment by kkellerlbl** [comment]
Yes, the ujs mongo user exists, and I've added a next njsw config file to Gitlab.  We'll need to do the same for appdev and production but we'll do that when we're ready to deploy.

**Comment by sychan** [comment]
I think its far enough along to give it a try.

**Comment by kkellerlbl** [comment]
Merging now so we don't get too many more commits on master.

**Pull request merged**
