### PR TITLE
Support for "cancelJob" API call. Fix for bug with several runs of the same job.

### PR DESCRIPTION
**Pull request by rsutormin**

### CODE REVIEW

**Comment by MrCreosote** [comment]
Tests pass; I'll take a look at the code tomorrow.

**Comment by MrCreosote** [comment]
OK, here's my feedback:

- it's really hard to understand why the new test is doing what it's doing. Some comments explaining the code would help a lot.
- finishJob should check if the user making the call is the same as the job owner prior to updating the database. Currently it will throw an error when updating the UJS, but it'll update the NJSW database with whatever data the caller sent before that.
- When a job is cancelled, the UJS state should probably be set to cancelled rather than done.
- There are a number of places where bracketless blocks are used. This coding style caused the heartbleed bug, so I'd strongly recommend using brackets.

**Comment by MrCreosote** [comment]
Sorry, the bug was the SSL gotofail bug, not heartbleed.

https://www.imperialviolet.org/2014/02/22/applebug.html

**Comment by rsutormin** [comment]
@MrCreosote: good points (except perhaps last one which in my opinion is more matter of taste).

**Comment by MrCreosote** [comment]
Obviously we disagree on the last point, but it's your repo, so merging.

**Pull request merged**
